apiVersion: v1
kind: Pod
metadata:
  name: powerlibrary-books-frontend
  labels:
    app.powerlibrary.io/name: books-frontend
spec:
  containers:
    - name: pl-books-frontend-v1
      imagePullPolicy: Never
      image: pl-books-frontend-v1
      ports:
        - containerPort: 3000
