apiVersion: v1
kind: Pod
metadata:
  name: powerlibrary-books-backend
  labels:
    app.powerlibrary.io/name: books-backend
spec:
  containers:
    - name: books-backend
      imagePullPolicy: Never
      image: pl-books-v1
      ports:
        - containerPort: 8000
      resources:
        requests:      
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name: books-database
      imagePullPolicy: Never
      image: pl-books-postgres:13
      env:
        - name: POSTGRES_PASSWORD
          value: test1
        - name: POSTGRES_USER
          value: raphael
        - name: POSTGRES_DB
          value: powerlibrary
      ports:
        - containerPort: 5432
      resources:
        requests:      
          memory: "1Gi"
          cpu: "250m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      volumeMounts:
        - name: pl-books-persistent-storage
          mountPath: /var/lib/postgresql/data
  volumes:
  - name: pl-books-persistent-storage
    persistentVolumeClaim:
      claimName: pl-books-pvc