apiVersion: v1
kind: Service
metadata:
  name: pl-books-backend-service
spec:
  selector:
    app.powerlibrary.io/name: books-backend
  ports:
    - name: pl-books-backend-port
      protocol: TCP
      port: 8000
      targetPort: 8000