apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pl-books-pvc
  labels:
    app.powerlibrary.io/name: books-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "powerlibrary-scn"