apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pl-shelfs-pvc
  labels:
    app.powerlibrary.io/name: shelfs-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "powerlibrary-shelfs-scn"