apiVersion: v1
kind: Pod
metadata:
  name: powerlibrary-shelfs-backend
  labels:
    app.powerlibrary.io/name: shelfs-backend
spec:
  containers:
    - name: shelfs-backend
      image: pl-shelfs-v1
      ports:
        - containerPort: 8081
      resources:
        requests:      
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
